# This is a basic workflow to help you get started with Actions

name: Check websites inside OSM database elements and report the problems encountered

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 00 * * 0'
    - cron:  '00 02 * * 0'
    - cron:  '00 04 * * 0'
    - cron:  '00 06 * * 0'
    - cron:  '00 08 * * 0'
    - cron:  '00 10 * * 0'
    - cron:  '00 12 * * 0'
    
    
    - cron:  '00 00 * * 1'
    - cron:  '00 02 * * 1'
    - cron:  '00 04 * * 1'
    - cron:  '00 06 * * 1'
    - cron:  '00 08 * * 1'
    - cron:  '00 10 * * 1'
    - cron:  '00 12 * * 1'
    
    - cron:  '00 00 * * 2'
    - cron:  '00 04 * * 2'
    - cron:  '00 08 * * 2'
    - cron:  '00 12 * * 2'
    - cron:  '00 16 * * 2'
    
    - cron:  '00 12 * * 3'    
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl parallel
          version: 1.0
      - name: preparation
        run: |
          mkdir -p ./log
          mkdir -p ./out
          
      - name: Siciliy
        if: github.event.schedule == '00 00 * * 0'
        run: |
          bash ./src/check-websites.sh Sicily >./out/results_Sicily.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted
          echo Sicily >./tmp/current_region.txt
      - name: Sardinia
        if: github.event.schedule == '00 02 * * 0'
        run: |
          bash ./src/check-websites.sh Sardinia >./out/results_Sardinia.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted
          echo Sardinia >./tmp/current_region.txt
      - name: Tuscany
        if: github.event.schedule == '00 04 * * 0'
        run: |
          bash ./src/check-websites.sh Tuscany >./out/results_Tuscany.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted
          echo  Tuscany >./tmp/current_region.txt
      - name: Lazio
        if: github.event.schedule == '00 06 * * 0'
        run: |
          bash ./src/check-websites.sh Lazio >./out/results_Lazio.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted
          echo Lazio >./tmp/current_region.txt
      - name: Umbria
        if: github.event.schedule == '00 08 * * 0'
        run: |
          bash ./src/check-websites.sh Umbria >./out/results_Umbria.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted
          echo Umbria >./tmp/current_region.txt
      - name: Marche
        if: github.event.schedule == '00 10 * * 0'
        run: |
          bash ./src/check-websites.sh Marche >./out/results_Marche.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted          
          echo Marche >./tmp/current_region.txt
      - name: Abruzzo
        if: github.event.schedule == '00 12 * * 0'
        run: |
          bash ./src/check-websites.sh Abruzzo >./out/results_Abruzzo.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted          
          echo Abruzzo >./tmp/current_region.txt

      - name: Apulia
        if: github.event.schedule == '00 00 * * 1'
        run: |
          bash ./src/check-websites.sh Apulia >./out/results_Apulia.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                    
          echo Apulia >./tmp/current_region.txt
      - name: Calabria
        if: github.event.schedule == '00 02 * * 1'
        run: |
          bash ./src/check-websites.sh Calabria >./out/results_Calabria.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                              
          echo Calabria >./tmp/current_region.txt
      - name: Basilicata
        if: github.event.schedule == '00 04 * * 1'
        run: |
          bash ./src/check-websites.sh Basilicata >./out/results_Basilicata.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                              
          echo Basilicata >./tmp/current_region.txt
      - name: Campania
        if: github.event.schedule == '00 06 * * 1'
        run: |
          bash ./src/check-websites.sh Campania >./out/results_Campania.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Campania >./tmp/current_region.txt
      - name: Molise
        if: github.event.schedule == '00 08 * * 1'
        run: |
          bash ./src/check-websites.sh Molise >./out/results_Molise.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Molise >./tmp/current_region.txt
      - name: Piedmont
        if: github.event.schedule == '00 10 * * 1'
        run: |
          bash ./src/check-websites.sh Piedmont >./out/results_Piedmont.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Piedmont >./tmp/current_region.txt
      - name: Emilia-Romagna
        if: github.event.schedule == '00 12 * * 1'
        run: |
          bash ./src/check-websites.sh Emilia-Romagna >./out/results_Emilia-Romagna.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Emilia Romagna >./tmp/current_region.txt

      - name: Liguria
        if: github.event.schedule == '00 00 * * 2'
        run: |
          bash ./src/check-websites.sh Liguria >./out/results_Liguria.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Liguria >./tmp/current_region.txt
      - name: Aosta_Valley
        if: github.event.schedule == '00 04 * * 2'
        env:
          region: Aosta Valley
        run: |
          bash ./src/check-websites.sh Aosta_Valley >./out/results_Aosta_Valley.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Aosta Valley >./tmp/current_region.txt
      - name: Veneto
        if: github.event.schedule == '00 08 * * 2'
        run: |
          bash ./src/check-websites.sh Veneto >./out/results_Veneto.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Veneto >./tmp/current_region.txt
      - name: Trentino-Alto_Adige
        if: github.event.schedule == '00 12 * * 2'
        run: |
          bash ./src/check-websites.sh Trentino-Alto_Adige >./out/results_Trentino-Alto_Adige.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Trentino Alto Adige >./tmp/current_region.txt
      - name: Friuli-Venezia_Giulia
        if: github.event.schedule == '00 16 * * 2'
        run: |
          bash ./src/check-websites.sh Friuli-Venezia_Giulia >./out/results_Friuli-Venezia_Giulia.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                                  
          echo Friuli Venezia Giulia >./tmp/current_region.txt
      
      - name: Lombardy
        if: github.event.schedule == '00 12 * * 3'
        run: |
          bash ./src/check-websites.sh Lombardy >./out/results_Lombardy.lst || echo "Bash script exited with error code $?" >>./log/action_$(date -Imin).halted                                        
          echo Lombardy >./tmp/current_region.txt
          
      # push changes to GITHUB
      - name: push changes
        run: |
          git config --local user.email "ricloy@users.noreply.github.com"
          git config --local user.name "actionman"
          git add -A
          git commit -m "Updated $(cat ./tmp/current_region); websites count: $(cat $(ls -1tr ./tmp/*_elements_website.lst | tail -n1) | wc -l) (of which unique: $(cat $(ls -1tr ./tmp/*_websites_checked.lst | tail -n1) | wc -l))" || exit 0
          git push
